//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object()
        {
            this.Request = new HashSet<Request>();
        }
    
        public int id_object { get; set; }
        public string name { get; set; }
        public int id_client { get; set; }
        public string code_type { get; set; }
        public string registration_number { get; set; }
        public string manufacturer { get; set; }
        public string model { get; set; }
        public string body_type { get; set; }
        public string engine { get; set; }
        public Nullable<int> year { get; set; }
        public string other { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Object_type Object_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
    }
}
