//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Activity = new HashSet<Activity>();
        }
    
        public int id_request { get; set; }
        public string description { get; set; }
        public string result { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date_request { get; set; }
        public Nullable<System.DateTime> date_fin_cancel { get; set; }
        public Nullable<int> id_object { get; set; }
        public Nullable<int> id_personel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activity { get; set; }
        public virtual Object Object { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
